# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            GIGABITCOIN
tagline:          Big On Bitcoin
url:              http://gigabitcoin.co
paginate:         1
baseurl:          /

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/gigabitcoin/gigabitcoin.githubpages.io
