# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /blog/:title


# Setup
title:            GIGABITCOIN
tagline:          Big On Bitcoin
url:              http://gigabitcoin.co

author:
  url: twitter.com/gigabitcoin

paginate:         1

# Custom vars
version:          1.0.0
github:
  repo:           github.com/gigabitcoin/gigabitcoin.githubpages.io

# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
