# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        none


# Setup
title:            GIGABITCOIN
tagline:          Big On Bitcoin
url:              http://gigabitcoin.co

author:
  url:            twitter.com/gigabitcoin

paginate:         1
baseurl:          /

# Custom vars
version:          1.0.0
github:
  repo:           github.com/gigabitcoin/gigabitcoin.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
